export const initialSliderObj = [
    {
        name: "Ringo Starr",
        bestSong: "Octopus man",
        image: "https://i.pinimg.com/originals/1f/e1/ba/1fe1ba78b87996d725d33c21d524220a.jpg",
    },
    {
        name: "Jhon Lennon",
        bestSong: "Strawberry field forever",
        image: "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_15.jpg",
    },
    {
        name: "Paul McCartney",
        bestSong: "Rocky Raccoon",
        image: "https://i.pinimg.com/originals/1d/37/18/1d37184dc0dccfab7e55ed968c0edc24.jpg",
    },
    {
        name: "George Harrison",
        bestSong: "Here comes the sun",
        image: "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/original_14.jpg",
    },
]

export const initialDiscography = [
    {
        name: "Please Please Me",
        image: "https://upload.wikimedia.org/wikipedia/en/c/c0/PleasePleaseMe_audio_cover.jpg",
        release: new Date(1963, 3, 22),
        track: [
            "I Saw Her Standing There",
            "Misery",
            "Anna",
            "Chains",
            "Boys",
            "Ask Me Why",
            "Please Please Me",
            "Love Me Do",
            "P.S. I Love You",
            "Baby It's You",
            "Do You Want To Know A Secret",
            "A Taste Of Honey",
            "There's A Place",
            "Twist and Shout",
        ]
    },
    {
        name: "With the Beatles",
        image: "https://upload.wikimedia.org/wikipedia/en/0/0a/Withthebeatlescover.jpg",
        release: new Date(1963, 11, 22),
        track: [
            "It Won't Be Long",
            "All I've Got To Do",
            "All My Loving ",
            "Don't Bother Me",
            "Little Child",
            "Till There Was You",
            "Please Mister Postman",
            "Roll Over Beethoven",
            "Hold Me Tight",
            "You Really Got A Hold On Me",
            "Devil In Her Heart",
            "Not A Second Time",
            "Money (That's What I Want)",
        ]
    },
    {
        name: "A Hard Day's Night",
        image: "https://upload.wikimedia.org/wikipedia/en/e/e6/HardDayUK.jpg",
        release: new Date(1964, 7, 10),
        track: [
            "A Hard Day's Night",
            "I Should Have Known Better",
            "If I Fell",
            "I'm Happy Just To Dance With You",
            "And I Love Her",
            "Tell Me Why",
            "Can't Buy Me Love",
            "Any Time At All",
            "I'll Cry Instead",
            "Things We Said Today",
            "When I Get Home",
            "You Can't Do That",
            "I'll Be Back",
        ]
    },
    {
        name: "Beatles for sale",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Beatlesforsale.jpg/220px-Beatlesforsale.jpg",
        release: new Date(1964, 12, 4),
        track: [
            "No Reply",
            "I'm a Loser",
            "Baby's in Black",
            "Rock and Roll Music",
            "I'll Follow the Sun",
            "Mr. Moonlight",
            "Kansas City / Hey-Hey-Hey-Hey",
            "Eight Days a Week",
            "Words of Love",
            "Honey Don't",
            "Every Little Thing",
            "I Don't Want to Spoil the Party",
            "What You're Doing",
            "Everybody's Trying to Be My Baby",
        ]
    },
    {
        name: "Help!",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Help%21_%28The_Beatles_album_-_cover_art%29.jpg/220px-Help%21_%28The_Beatles_album_-_cover_art%29.jpg",
        release: new Date(1965, 8, 6),
        track: [
            "Help!",
            "The Night Before",
            "You've Got To Hide Your Love Away",
            "I Need You",
            "Another Girl",
            "You're Going To Lose That Girl",
            "Ticket To Ride",
            "Act Naturally",
            "It's Only Love",
            "You Like Me Too Much",
            "Tell Me What You See",
            "I've Just Seen A Face",
            "Yesterday",
            "Dizzy Miss Lizzy",
        ]
    },
    {
        name: "Rubber Soul",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Rubber_Soul.jpg/220px-Rubber_Soul.jpg",
        release: new Date(1965, 12, 3),
        track: [
            "Drive My Car",
            "Norwegian Wood (This Bird Has Flown)",
            "You Won't See Me",
            "Nowhere Man",
            "Think For Yourself",
            "The Word",
            "Michelle",
            "What Goes On",
            "Girl",
            "I'm Looking Through You",
            "In My Life",
            "Wait",
            "If I Needed Someone",
            "Run For Your Life",
        ]
    },
    {
        name: "Revolver",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Revolver.jpg/220px-Revolver.jpg",
        release: new Date(1966, 8, 5),
        track: [
            "Taxman",
            "Eleanor Rigby",
            "I'm Only Sleeping",
            "Love You To",
            "Here, There and Everywhere",
            "Yellow Submarine",
            "She Said, She Said",
            "Good Day Sunshine",
            "And Your Bird Can Sing",
            "For No One",
            "Doctor Robert",
            "I Want To Tell You",
            "Got To Get You Into My Life",
            "Tomorrow Never Knows",
        ]
    },
    {
        name: "Sgt. Pepper's Lonely Hearts Club Band",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Sgt._Pepper%27s_Lonely_Hearts_Club_Band.jpg/220px-Sgt._Pepper%27s_Lonely_Hearts_Club_Band.jpg",
        release: new Date(1967, 5, 26),
        track: [
            "Sgt. Pepper's Lonely Hearts Club Band",
            "With A Little Help From My Friends",
            "Lucy in the Sky with Diamonds",
            "Getting Better",
            "Fixing A Hole",
            "She's Leaving Home",
            "Being For The Benefit of Mr.Kite!",
            "Within You Without You",
            "When I'm Sixty-Four",
            "Lovely Rita",
            "Good Morning Good Morning",
            "Sgt. Pepper's Lonely Hearts Club Band (Reprise)",
            "A Day in the Life",
        ]
    },
    {
        name: "Magical Mystery Tour",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/MagicalMysteryTourDoubleEPcover.jpg/220px-MagicalMysteryTourDoubleEPcover.jpg",
        release: new Date(1967, 12, 8),
        track: [
            "Magical Mystery Tour",
            "The Fool on the Hill",
            "Flying",
            "Blue Jay Way",
            "Your Mother Should Know",
            "I Am the Walrus",
            "Hello Goodbye",
            "Strawberry Fields Forever",
            "Penny Lane",
            "Baby You're a Rich Man",
            "All You Need Is Love",
        ]
    },
    {
        name: "The Beatles",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/TheBeatles68LP.jpg/220px-TheBeatles68LP.jpg",
        release: new Date(1968, 11, 22),
        track: [
            "Back in the U.S.S.R",
            "Dear Prudence",
            "Glass Onion",
            "Ob-La-Di, Ob-La-Da",
            "Wild Honey Pie",
            "The Continuing Story Of Bungalow Bill",
            "While My Guitar Gently Weeps",
            "Happiness Is a Warm Gun",
            "Martha My Dear",
            "I′m So Tired",
            "Blackbird",
            "Piggies",
            "Rocky Raccoon",
            "Don't Pass Me By",
            "Why Don't We Do It In The Road",
            "I Will",
            "Julia",
            "Birthday",
            "Yer Blues",
            "Mother Nature's Son",
            "Everybody's Got Something To Hide Except Me And My Monkey",
            "Sexy Sadie",
            "Helter Skelter",
            "Long, Long, Long",
            "Revolution 1",
            "Honey Pie",
            "Savoy Truffle",
            "Cry Baby Cry",
            "Revolution 9",
            "Good Night",
        ]
    },
    {
        name: "Yellow Submarine",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/TheBeatles-YellowSubmarinealbumcover.jpg/220px-TheBeatles-YellowSubmarinealbumcover.jpg",
        release: new Date(1969, 1, 13),
        track: [
            "Yellow Submarine",
            "Only a Northern Song",
            "All Together Now",
            "Hey Bulldog",
            "It's All Too Much",
            "All You Need Is Love",
            "Pepperland",
            "Sea of Time",
            "Sea of Holes",
            "Sea of Monsters",
            "March of the Meanies",
            "Pepperland Laid Waste",
            "Yellow Submarine in Pepperland",
        ]
    },
    {
        name: "Abbey Road",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Beatles_-_Abbey_Road.jpg/220px-Beatles_-_Abbey_Road.jpg",
        release: new Date(1969, 9, 26),
        track: [
            "Come Together",
            "Something",
            "Maxwell's Silver Hammer",
            "Oh! Darling",
            "Octopus's Garden",
            "I Want You (She's So Heavy)",
            "Here Comes The Sun",
            "Because",
            "You Never Give Me Your Money",
            "Sun King",
            "Mean Mr. Mustard",
            "Polythene Pam",
            "She Came in Through the Bathroom Window",
            "Golden Slumbers",
            "Carry That Weight",
            "The End",
            "Her Majesty",
            "The Long One",
        ]
    },
    {
        name: "Let It Be ",
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/2/25/LetItBe.jpg/220px-LetItBe.jpg",
        release: new Date(1970, 5, 8),
        track: [
            "Two of Us",
            "Dig a Pony",
            "Across The Universe",
            "I Me Mine",
            "Dig It",
            "Let It Be",
            "Maggie Mae",
            "I've Got a Feeling",
            "One After 909",
            "The Long and Winding Road",
            "For You Blue",
            "Get Back",
        ]
    },
]